resources:
  repositories:
    - name: remote-templates
      uri: git@github.com:tmobile/POET-pipeline-demo.git
      # label is optional (defaults to master), and can reference branch, tag, commit
      label: feature/templates      
      # Note that credentials details may change based on how they are setup on your Pipeline Engine
      credentials:
        id: SSH_Key_GitHub

pipeline:
  appName: poet-test
  appVersion:
    master: 1.0.0
  steps:
    - name: hello-poet
      image: bash
      commands:
        - ls -lrta
        - echo "Hello POET!!!"
    # Remote templated step: Ruby    
    - include: templates/ruby-step.yml@remote-templates
    # Remote templated step: Python
    - include: templates/python-step.yml@remote-templates
