pipeline:
  appName: poet-demo
  appVersion:
    master: 1.0.0
  steps:
    - name: hello-poet
      image: bash
      commands:
        - ls -lrta
        - echo "Hello POET!!!"
    - name: templated-python
      image: python:3.5.7-alpine
      commands:
        - python -v
    - name: templated-ruby
      image: ruby:2.5-alpine
      commands:
        - ruby -v
